### ISSUE TITLE
Does this work with recent versions of Zotero?

### ISSUE THREAD

**Issue by qlyoung** [foxsen/zotero-selfhost#3]
I'm interested in deploying this and would like to know if anyone's successfully using it with recent (6+) versions of Zotero.

**Comment by schnadoslin** [comment]
Did you get it to work? Does it work with the current version?

**Comment by qlyoung** [comment]
No, I decided to use syncthing to sync the zotero data folder between devices instead. Works okay. I didn't try this project.
